config/routes.rb
Rails.application.routes.draw do
  

  root "meetings#index"
  
  
  
  resources :meetings do
    resources :heats
    resources :home_riders
    resources :away_riders
    get 'static_pages/rider'
    get 'static_pages/gate'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def gate
    find_meeting
  end

  def rider
      find_meeting
  end
  
  private
  
  def find_meeting
    @meeting = Meeting.find(params[:meeting_id])
  end
  

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    
    def gate_results(meeting, gate_number)
        
        if meeting.heats.present?
            red = meeting.heats.where(red_gate: gate_number).sum(:red_score)
            blue = meeting.heats.where(blue_gate: gate_number).sum(:blue_score)
            white = meeting.heats.where(white_gate: gate_number).sum(:white_score)
            yellow = meeting.heats.where(yellow_gate: gate_number).sum(:yellow_score)
            
            score = red + blue + white + yellow
        else
            score = 0
        end
    end
    

    
    def getHomeRiderStats(meeting, rider)
        if meeting.heats.present?
            score = meeting.heats.where(blue_rider: rider).sum(:blue_score) + meeting.heats.where(red_rider: rider).sum(:red_score)
        else
            score = 0
        end
    end
    
    def getAwayRiderStats(meeting, rider)
        if meeting.heats.present?
            score = meeting.heats.where(white_rider: rider).sum(:white_score) + meeting.heats.where(yellow_rider: rider).sum(:yellow_score)
        else
            score = 0
        end
    end

end
  

app/views/static_pages/gate.html.erb
<div class="row">
    <div class="col text-center">Gate statistics</div>
</div> 
<hr>
<table class="table table-hover table-sm">
    <thead class="thead-light">
        <tr>
            <th>Gate</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td><%= gate_results(@meeting, 1) %></td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td><%= gate_results(@meeting, 2) %></td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td><%= gate_results(@meeting, 3) %></td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td><%= gate_results(@meeting, 4) %></td>
        </tr>
    </tbody>
</table>

<div class="row">
    <div class="col-sm-12">
        <%= button_to "Back", meeting_path(@meeting), method: :get, class: "btn btn-secondary btn-block" %>
    </div>
</div>

app/views/static_pages/rider.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h5><%= @meeting.date.strftime("%a %b %d") %></h5>
    </div>
  </div>
</div>


<table class="table table-hover table-sm table-bordered">
    <thead class="thead-light">
        <tr>
            <th>#</th>
            <th><%= @meeting.home_team_name %></td>
            <th>Total</td>
            <th><%= @meeting.away_team_name %></td>
            <th>Total</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td><%= @meeting.home_riders.home_rider_1 %></td>
            <td><%= getHomeRiderStats(@meeting, @meeting.home_riders.home_rider_1) %></td>
            <td><%= @meeting.away_riders.away_rider_1 %></td>
            <td><%= getAwayRiderStats(@meeting, @meeting.away_riders.away_rider_1) %></td>
        </tr>
        
        <tr>
            <th scope="row">2</th>
            <td><%= @meeting.home_riders.home_rider_2 %></td>
            <td><%= getHomeRiderStats(@meeting, @meeting.home_riders.home_rider_2) %></td>
            <td><%= @meeting.away_riders.away_rider_2 %></td>
            <td><%= getAwayRiderStats(@meeting, @meeting.away_riders.away_rider_2) %></td>
        </tr>
        
        <tr>
            <th scope="row">3</th>
            <td><%= @meeting.home_riders.home_rider_3 %></td>
            <td><%= getHomeRiderStats(@meeting, @meeting.home_riders.home_rider_3) %></td>
            <td><%= @meeting.away_riders.away_rider_3 %></td>
            <td><%= getAwayRiderStats(@meeting, @meeting.away_riders.away_rider_3) %></td>
        </tr>
        
        <tr>
            <th scope="row">4</th>
            <td><%= @meeting.home_riders.home_rider_4 %></td>
            <td><%= getHomeRiderStats(@meeting, @meeting.home_riders.home_rider_4) %></td>
            <td><%= @meeting.away_riders.away_rider_4 %></td>
            <td><%= getAwayRiderStats(@meeting, @meeting.away_riders.away_rider_4) %></td>
        </tr>
        
        <tr>
            <th scope="row">5</th>
            <td><%= @meeting.home_riders.home_rider_5 %></td>
            <td><%= getHomeRiderStats(@meeting, @meeting.home_riders.home_rider_5) %></td>
            <td><%= @meeting.away_riders.away_rider_5 %></td>
            <td><%= getAwayRiderStats(@meeting, @meeting.away_riders.away_rider_5) %></td>
        </tr>
        
        <tr>
            <th scope="row">6</th>
            <td><%= @meeting.home_riders.home_rider_6 %></td>
            <td><%= getHomeRiderStats(@meeting, @meeting.home_riders.home_rider_6) %></td>
            <td><%= @meeting.away_riders.away_rider_6 %></td>
            <td><%= getAwayRiderStats(@meeting, @meeting.away_riders.away_rider_6) %></td>
        </tr>
        
        <tr>
            <th scope="row">7</th>
            <td><%= @meeting.home_riders.home_rider_7 %></td>
            <td><%= getHomeRiderStats(@meeting, @meeting.home_riders.home_rider_7) %></td>
            <td><%= @meeting.away_riders.away_rider_7 %></td>
            <td><%= getAwayRiderStats(@meeting, @meeting.away_riders.away_rider_7) %></td>
        </tr>
        
    </tbody>
</table>

<div class="row">
    <div class="col-sm-12">
        <%= button_to "Back", meeting_path(@meeting), method: :get, class: "btn btn-secondary btn-block" %>
    </div>
</div>