config/routes.rb
Rails.application.routes.draw do
  

  root "meetings#index"
  
  
  
  resources :meetings do
    resources :heats
    resources :home_riders
    resources :away_riders
    get 'static_pages/rider'
    get 'static_pages/gate'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting
  include Mongoid::Document
  field :home_team_name, type: String
  field :away_team_name, type: String
  field :gate, type: String
  field :date, type: Date
  embeds_many :heats
  embeds_one :home_riders
  embeds_one :away_riders
  accepts_nested_attributes_for :heats, :home_riders, :away_riders, autosave: true
  validates :date, :home_team_name, :away_team_name, presence: true
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  def index
    @meetings = Meeting.all.order(date: :desc)
  end

  # GET /meetings/1
  def show
    @home_rider = @meeting.home_riders
    @away_rider = @meeting.away_riders
    @heat = @meeting.heats
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
    @team_names = Team.distinct(:team_name)
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /meetings/1
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /meetings/1
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:home_team_name, :away_team_name, :date, :gate, 
                                      heat_attributes: [:heat_number, :heat_time,
                                       :red_gate, :red_score, :red_rider,
                                       :blue_gate, :blue_score, :blue_rider,
                                       :white_gate, :white_score, :white_rider,
                                       :yellow_gate, :yellow_score, :yellow_rider],
                                       home_riders_attributes: [:home_rider_1, :home_rider_2,
                                       :home_rider_3, :home_rider_4, :home_rider_5,
                                       :home_rider_6, :home_rider_7])
    end
end
 

app/helpers/meetings_helper.rb
module MeetingsHelper
    
    def home_score
        if @meeting.heats.present?
            score = @meeting.heats.sum(:blue_score) + @meeting.heats.sum(:red_score)
        else
            score = 0
        end
    end
    
    def away_score
        if @meeting.heats.present?
            score = @meeting.heats.sum(:white_score) + @meeting.heats.sum(:yellow_score)
        else
            score = 0
        end
    end
    
end

app/views/meetings/_form.html.erb
<%= simple_form_for @meeting do |f| %>
  <%= f.input :date, as: :string, placeholder: "#{Date.today}" %>
  <%= f.input :home_team_name, collection: @team_names %>
  <%= f.input :away_team_name, collection: @team_names %>
  <%= f.input :gate, collection: ["1 and 3", "2 and 4"], input_html:{disabled: @meeting.heats.present?} %>
  <%= f.submit %>
<% end %>

app/views/meetings/edit.html.erb
<h3>Edit Meeting</h3>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row ">
  <div class="col-md-12">
    <div class="page-header"><h3>Meetings</h3></div>
  </div>
</div>

<div class="row ">
  <div class="col-md-12">
    <%= button_to "Add meeting", new_meeting_path, method: :get, class: "btn btn-small btn-block" %>
  </div>
</div>

<% @meetings.each do |meeting| %>
<hr>
<div class="row">
  <div class="col-md-12">
      <%= button_to meeting.date.strftime("%a %b %d"), meeting, method: :get, class: "btn btn-info btn-block" %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="d-flex bd-highlight">
      <div class="p-2 flex-fill bd-highlight"><%= meeting.home_team_name %></div>
      <div class="p-2 flex-fill bd-highlight"><%= meeting.away_team_name %></div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="d-flex bd-highlight">
      <div class="p-2 flex-fill bd-highlight">
        <%= button_to 'Edit', edit_meeting_path(meeting), class: 'btn btn-sm btn-outline-secondary', method: :get %>
      </div>
      <div class="p-2 flex-fill bd-highlight">
        <%= button_to 'Delete', meeting, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/meetings/new.html.erb
<h3>New Meeting</h3>

<%= render 'form', meeting: @meeting %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h5><%= @meeting.date.strftime("%a %b %d") %></h5>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="d-flex bd-highlight">
      <div class="p-2 flex-fill bd-highlight"><h5><%= @meeting.home_team_name %>: <%= home_score %></h5></div>
      <div class="p-2 flex-fill bd-highlight"><h5><%= @meeting.away_team_name %>: <%= away_score %></h5></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="d-flex bd-highlight">
      
      <div class="p-2 flex-fill bd-highlight">
        <nav class="nav nav-pills nav-justified justify-content-center">
          <%= @meeting.home_riders.nil? ? 
                (button_to 'Add riders', new_meeting_home_rider_path(@meeting, @home_rider), class: "btn btn-sm btn-success", method: :get) : 
                (button_to 'Edit riders', edit_meeting_home_rider_path(@meeting, @home_rider ), class: "btn btn-sm btn-outline-dark", method: :get) %>
        </nav>
      </div>
      <div class="p-2 flex-fill bd-highlight">
        <nav class="nav nav-pills nav-justified justify-content-center">
          <%= @meeting.away_riders.nil? ? 
                (button_to 'Add riders', new_meeting_away_rider_path(@meeting, @away_rider), class: "btn btn-sm btn-success", method: :get) : 
                (button_to 'Edit riders', edit_meeting_away_rider_path(@meeting, @away_rider ), class: "btn btn-sm btn-outline-dark", method: :get) %>
        </nav>
      </div>
      
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="d-flex bd-highlight">
      
      <div class="p-2 flex-fill bd-highlight">
        <nav class="nav nav-pills nav-justified justify-content-center">
          <%= button_to "Rider stats", meeting_static_pages_rider_path(@meeting), method: :get, class: "btn btn-sm btn-info"  %>
        </nav>
      </div>
      <div class="p-2 flex-fill bd-highlight">
        <nav class="nav nav-pills nav-justified justify-content-center">
          <%= button_to "Gate stats", meeting_static_pages_gate_path(@meeting), method: :get, class: "btn btn-sm btn-info"  %>
        </nav>
      </div>
      
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <hr>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <%= (@meeting.home_riders.nil? || @meeting.away_riders.nil?) ? 
      (button_to 'Add heat', new_meeting_heat_path(@meeting), class: "btn btn-small btn-block btn-success", disabled: true)  :
      (button_to 'Add heat', new_meeting_heat_path(@meeting), class: "btn btn-small btn-block btn-success", method: :get) %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <hr>
  </div>
</div>

<% @meeting.heats.each do |f| %>

<div class="row">
    <div class="col-sm-12">
      <%= button_to "Heat #{f.heat_number}: Time #{f.heat_time}", edit_meeting_heat_path(@meeting, f), method: :get, class: "btn btn-outline-secondary btn-block" %>
      <br>
    </div>
</div>


<% end %>

<hr>